# -*- coding: utf-8 -*-
S_DEFAULT = True
S_DEFAULT_PROJECT = False
S_DEFAULT_USER = False
S_DEFAULT_PROJECT_USER = False

S_DEFAULT_INI = False
S_DEFAULT_PROJECT_INI = False
S_DEFAULT_INI_USER = False
S_DEFAULT_PROJECT_INI_USER = False
