# -*- coding: utf-8 -*-
S_PROJECT = True
S_DEFAULT_PROJECT = True
S_DEFAULT_PROJECT_USER = False
S_PROJECT_USER = False

S_PROJECT_INI = False
S_DEFAULT_PROJECT_INI = False
S_DEFAULT_PROJECT_INI_USER = False
S_PROJECT_INI_USER = False

S_BASE_LIST = [1, ]
