# Generated by Django 2.1 on 2018-08-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("djangofloor", "0002_notification_notificationread")]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="is_active",
            field=models.BooleanField(
                blank=True,
                db_index=True,
                default=True,
                help_text="Only active notifications will be displayed.",
                verbose_name="Is active?",
            ),
        )
    ]
